from enum import Enum

class ConversationState(str, Enum):
    NEW_USER = "NEW_USER"
    WAITING_TNC_ACCEPTANCE = "WAITING_TNC_ACCEPTANCE"
    WAITING_SCENE_SELECTION = "WAITING_SCENE_SELECTION"
    WAITING_USER_NAME = "WAITING_USER_NAME"
    WAITING_USER_GENDER = "WAITING_USER_GENDER"
    WAITING_USER_PICTURE = "WAITING_USER_PICTURE"
    WAITING_CONSENT_CONFIRMATION = "WAITING_CONSENT_CONFIRMATION"
    WAITING_BUDDY_NAME = "WAITING_BUDDY_NAME"
    WAITING_BUDDY_GENDER = "WAITING_BUDDY_GENDER"
    WAITING_BUDDY_PICTURE = "WAITING_BUDDY_PICTURE"
    WAITING_BUDDY_APPROVAL = "WAITING_BUDDY_APPROVAL"
    READY_FOR_API_CALL = "READY_FOR_API_CALL"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class ConsentStatus(str, Enum):
    PENDING = "PENDING"
    GIVEN = "GIVEN"
    REVOKED = "REVOKED"

class BuddyApprovalStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
